### PR TITLE
Rsvp work

### PR DESCRIPTION
**Pull request by zanehirning**
What was done:
- Creating the open api spec for the rsvp endpoint
- Creating the endpoint and handling attendees
- Putting player onto the game's team roster

### CODE REVIEW

**Review by funkybooboo — APPROVED** [review]
Looks good Zane!

**Review by marcus-quincy — APPROVED** [review]
Looks good.

**Comment by epeterson42** [comment]
We had a conversation with Jacob a while ago about player rsvp-ing. He said that a game roster is a list of players that actually attended and that rsvp is potentially different. So we may need to add a flag to the roster model indicating if the player did rsvp and another if they actually attended.
I'd say we can call what you have good for now and maybe leave a few comments for whoever picks this up next.

**Comment by zanehirning** [comment]
> We had a conversation with Jacob a while ago about player rsvp-ing. He said that a game roster is a list of players that actually attended and that rsvp is potentially different. So we may need to add a flag to the roster model indicating if the player did rsvp and another if they actually attended. I'd say we can call what you have good for now and maybe leave a few comments for whoever picks this up next.

Sounds good. I'll add a couple of comments explaining this and then merge. Thanks.

**Pull request merged**
